server:
  port: 8080

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    show-sql: true
    defer-datasource-initialization: true

  h2:
    console.enabled: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka